### ISSUE TITLE
fix the captcha issue

### ISSUE THREAD

**Issue by AakashSasikumar** [killersamurai/YouTubeScraper#2]
this wont work if many requests are sent to the second website, it will ask for captcha.

**Comment by samuelteixeiras** [comment]
Hi , you could do the download to mp3 using this http://stackoverflow.com/questions/12436584/youtube-to-mp3-conversion-using-web-site.

**Comment by AakashSasikumar** [comment]
sorry i didn't get back to you earlier. I didn't want to go with that site plus a lot of others simply because this site offers better quality.
